<?php

use App\Http\Controllers\AbsenceCalendarController;
use App\Http\Controllers\ApprovalInboxController;
use App\Http\Controllers\Auth\CoreOAuthCallbackController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\OrganizationRegistrationController;
use App\Http\Controllers\Auth\StaffInviteAcceptController;
use App\Http\Controllers\BusinessSegmentController;
use App\Http\Controllers\ClockController;
use App\Http\Controllers\CompetencyController;
use App\Http\Controllers\ContractRegisterController;
use App\Http\Controllers\DocumentCreatorController;
use App\Http\Controllers\DocumentHandoverController;
use App\Http\Controllers\EmploymentContractController;
use App\Http\Controllers\EntranceClockController;
use App\Http\Controllers\ExceptionQueueController;
use App\Http\Controllers\ExpiryController;
use App\Http\Controllers\FamilyMemberController;
use App\Http\Controllers\GrantHoursController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InternalActController;
use App\Http\Controllers\KioskController;
use App\Http\Controllers\MyDocumentsController;
use App\Http\Controllers\OrganizationDashboardController;
use App\Http\Controllers\OrganizationLandingController;
use App\Http\Controllers\OrganizationPickerController;
use App\Http\Controllers\OrganizationSettingsController;
use App\Http\Controllers\OrganizationSuspendedController;
use App\Http\Controllers\OrganizationTeamController;
use App\Http\Controllers\OrgPositionController;
use App\Http\Controllers\PeopleRegisterController;
use App\Http\Controllers\PersonController;
use App\Http\Controllers\PersonDocumentController;
use App\Http\Controllers\PersonPrintController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\QualificationController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\SelectionController;
use App\Http\Controllers\StaffRequestController;
use App\Http\Controllers\StructureController;
use App\Http\Controllers\SystematizationController;
use App\Http\Controllers\TimesheetController;
use App\Http\Controllers\TimesheetReportController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/cijene', PricingController::class)->name('pricing');

Route::middleware('guest')->group(function () {
    Route::get('/prijava', [LoginController::class, 'create'])->name('login');
    Route::post('/prijava', [LoginController::class, 'store']);
    Route::get('/auth/core/callback', [CoreOAuthCallbackController::class, 'create'])->name('auth.core.callback');
    Route::get('/poziv/{token}', [StaffInviteAcceptController::class, 'show'])->name('staff-invite.show');
    Route::post('/poziv/{token}', [StaffInviteAcceptController::class, 'store'])->name('staff-invite.store');
});

Route::get('/registracija', [OrganizationRegistrationController::class, 'create'])->name('register.organization');
Route::post('/registracija', [OrganizationRegistrationController::class, 'store'])
    ->middleware('throttle:6,1');
Route::get('/registracija/sudski-registar', [OrganizationRegistrationController::class, 'courtRegisterLookup'])
    ->middleware('throttle:20,1')
    ->name('register.organization.court-register');

Route::middleware('auth')->group(function () {
    Route::post('/odjava', [LoginController::class, 'destroy'])->name('logout');
    Route::get('/registracija-ceka', [OrganizationRegistrationController::class, 'pending'])->name('registration.pending');
    Route::get('/registracija-ceka/stanje', [OrganizationRegistrationController::class, 'status'])->name('registration.pending.status');
    Route::get('/odabir-tvrtke', [OrganizationPickerController::class, 'index'])->name('organization.pick');
    Route::post('/odabir-tvrtke', [OrganizationPickerController::class, 'store'])->name('organization.pick.store');
    Route::get('/pristup-suspendiran/{slug}', [OrganizationSuspendedController::class, 'show'])->name('organization.suspended');
});

Route::prefix('{slug}')
    ->where(['slug' => '[a-z0-9\-]+'])
    ->middleware('kiosk')
    ->group(function () {
        Route::get('/kiosk/{token}', [KioskController::class, 'show'])->name('organization.kiosk');
        Route::post('/kiosk/{token}/pin', [KioskController::class, 'identify'])
            ->middleware('throttle:10,1')
            ->name('organization.kiosk.identify');
        Route::post('/kiosk/{token}/prijava', [KioskController::class, 'punch'])->name('organization.kiosk.punch');
        Route::post('/kiosk/{token}/odjava-ekrana', [KioskController::class, 'reset'])->name('organization.kiosk.reset');
    });

Route::prefix('{slug}')
    ->where(['slug' => '[a-z0-9\-]+'])
    ->middleware(['auth', 'organization'])
    ->group(function () {
        Route::get('/', OrganizationLandingController::class)->name('organization.landing');
        Route::get('/pregled', OrganizationDashboardController::class)->name('organization.dashboard');
        Route::get('/sistematizacija', [SystematizationController::class, 'index'])->name('organization.systematization.index');
        Route::get('/sistematizacija/plan', [OrgPositionController::class, 'plan'])->name('organization.systematization.plan');
        Route::get('/sistematizacija/kompetencije', [CompetencyController::class, 'index'])->name('organization.systematization.competencies');
        Route::post('/sistematizacija/kompetencije', [CompetencyController::class, 'store'])->name('organization.competencies.store');
        Route::delete('/sistematizacija/kompetencije/{competency}', [CompetencyController::class, 'destroy'])->name('organization.competencies.destroy');
        Route::post('/sistematizacija/kompetencije/veza', [CompetencyController::class, 'attach'])->name('organization.competencies.attach');
        Route::delete('/sistematizacija/kompetencije/veza', [CompetencyController::class, 'detach'])->name('organization.competencies.detach');
        Route::get('/sistematizacija/akti', [InternalActController::class, 'index'])->name('organization.systematization.acts');
        Route::post('/sistematizacija/akti', [InternalActController::class, 'store'])->name('organization.acts.store');
        Route::get('/sistematizacija/akti/{act}/preuzmi', [InternalActController::class, 'download'])->name('organization.acts.download');
        Route::delete('/sistematizacija/akti/{act}', [InternalActController::class, 'destroy'])->name('organization.acts.destroy');
        Route::get('/ustroj/segmenti', [BusinessSegmentController::class, 'index'])->name('organization.segments.index');
        Route::post('/ustroj/segmenti', [BusinessSegmentController::class, 'store'])->name('organization.segments.store');
        Route::put('/ustroj/segmenti/{segment}', [BusinessSegmentController::class, 'update'])->name('organization.segments.update');
        Route::delete('/ustroj/segmenti/{segment}', [BusinessSegmentController::class, 'destroy'])->name('organization.segments.destroy');
        Route::get('/ustroj/pozicije', [OrgPositionController::class, 'index'])->name('organization.positions.index');
        Route::post('/ustroj/pozicije', [OrgPositionController::class, 'store'])->name('organization.positions.store');
        Route::put('/ustroj/pozicije/{position}', [OrgPositionController::class, 'update'])->name('organization.positions.update');
        Route::delete('/ustroj/pozicije/{position}', [OrgPositionController::class, 'destroy'])->name('organization.positions.destroy');
        Route::get('/zaposlenici/ugovori', [ContractRegisterController::class, 'index'])->name('organization.contracts.index');
        Route::get('/zaposlenici/dokumenti', [DocumentCreatorController::class, 'index'])->name('organization.document-creator.index');
        Route::post('/zaposlenici/dokumenti', [DocumentCreatorController::class, 'store'])->name('organization.document-creator.store');
        Route::get('/zaposlenici/obitelj', [FamilyMemberController::class, 'index'])->name('organization.family.index');
        Route::post('/zaposlenici/obitelj', [FamilyMemberController::class, 'store'])->name('organization.family.store');
        Route::delete('/zaposlenici/obitelj/{member}', [FamilyMemberController::class, 'destroy'])->name('organization.family.destroy');
        Route::get('/moje/dokumenti', [MyDocumentsController::class, 'index'])->name('organization.my-documents.index');
        Route::get('/moje/dokumenti/{document}/preuzmi', [MyDocumentsController::class, 'download'])->name('organization.my-documents.download');
        Route::get('/postavke', [OrganizationSettingsController::class, 'index'])->name('organization.settings.index');
        Route::put('/postavke/organizacija', [OrganizationSettingsController::class, 'updateOrganization'])->name('organization.settings.organization');
        Route::put('/postavke/izgled', [OrganizationSettingsController::class, 'updateTheme'])->name('organization.settings.theme');
        Route::post('/postavke/logo', [OrganizationSettingsController::class, 'updateLogo'])->name('organization.settings.logo');
        Route::put('/postavke/volonteri', [OrganizationSettingsController::class, 'updateVolunteer'])->name('organization.settings.volunteer');
        Route::put('/postavke/isteci', [OrganizationSettingsController::class, 'updateExpiry'])->name('organization.settings.expiry');
        Route::post('/postavke/zadrzavanje/{document}/potvrdi', [OrganizationSettingsController::class, 'confirmRetention'])->name('organization.settings.retention.confirm');
        Route::put('/postavke/go', [OrganizationSettingsController::class, 'updateLeavePolicy'])->name('organization.settings.leave');
        Route::post('/postavke/go/pragovi', [OrganizationSettingsController::class, 'storeTenureRule'])->name('organization.settings.leave.rules.store');
        Route::delete('/postavke/go/pragovi/{rule}', [OrganizationSettingsController::class, 'destroyTenureRule'])->name('organization.settings.leave.rules.destroy');
        Route::post('/postavke/go/preracun', [OrganizationSettingsController::class, 'recalculateLeave'])->name('organization.settings.leave.recalculate');
        Route::put('/postavke/zakljucavanje', [OrganizationSettingsController::class, 'updatePeriodLock'])->name('organization.settings.period-lock');
        Route::post('/postavke/sifre', [OrganizationSettingsController::class, 'storeAbsenceCode'])->name('organization.settings.codes.store');
        Route::delete('/postavke/sifre/{code}', [OrganizationSettingsController::class, 'destroyAbsenceCode'])->name('organization.settings.codes.destroy');
        Route::post('/postavke/lokacije', [OrganizationSettingsController::class, 'storeLocation'])->name('organization.settings.locations.store');
        Route::put('/postavke/lokacije/{location}', [OrganizationSettingsController::class, 'updateLocation'])->name('organization.settings.locations.update');
        Route::get('/postavke/lokacije/{location}/kiosk', [OrganizationSettingsController::class, 'kioskPoster'])->name('organization.settings.locations.kiosk-qr');
        Route::get('/postavke/lokacije/{location}/ulaz', [OrganizationSettingsController::class, 'entrancePoster'])->name('organization.settings.locations.entrance-qr');
        Route::post('/postavke/dokumenti', [OrganizationSettingsController::class, 'storeDocumentType'])->name('organization.settings.document-types.store');
        Route::delete('/postavke/dokumenti/{documentType}', [OrganizationSettingsController::class, 'destroyDocumentType'])->name('organization.settings.document-types.destroy');
        Route::post('/postavke/slijedovi/{workflow}/koraci', [OrganizationSettingsController::class, 'storeWorkflowStep'])->name('organization.settings.workflow-steps.store');
        Route::delete('/postavke/slijedovi/{workflow}/koraci/{step}', [OrganizationSettingsController::class, 'destroyWorkflowStep'])->name('organization.settings.workflow-steps.destroy');
        Route::post('/postavke/predlosci', [OrganizationSettingsController::class, 'storeDocumentTemplate'])->name('organization.settings.templates.store');
        Route::get('/postavke/predlosci/{template}/preuzmi', [OrganizationSettingsController::class, 'downloadDocumentTemplate'])->name('organization.settings.templates.download');
        Route::delete('/postavke/predlosci/{template}', [OrganizationSettingsController::class, 'destroyDocumentTemplate'])->name('organization.settings.templates.destroy');
        Route::post('/postavke/uvoz', [OrganizationSettingsController::class, 'importPeople'])->name('organization.settings.import');
        Route::get('/postavke/uvoz/predlozak', [OrganizationSettingsController::class, 'importPeopleTemplate'])->name('organization.settings.import.template');
        Route::get('/prijava', [ClockController::class, 'show'])->name('organization.clock');
        Route::get('/prijava/manifest.webmanifest', [ClockController::class, 'manifest'])->name('organization.clock.manifest');
        Route::post('/prijava', [ClockController::class, 'store'])->name('organization.clock.store');
        Route::post('/api/clock/punches', [ClockController::class, 'store'])->name('organization.clock.api');
        Route::get('/ulaz/{token}', [EntranceClockController::class, 'show'])->name('organization.entrance');
        Route::post('/ulaz/{token}', [EntranceClockController::class, 'store'])->name('organization.entrance.store');
        Route::get('/struktura', [StructureController::class, 'index'])->name('organization.structure.index');
        Route::post('/struktura/odjeli', [StructureController::class, 'storeDepartment'])->name('organization.structure.departments.store');
        Route::put('/struktura/odjeli/{department}', [StructureController::class, 'updateDepartment'])->name('organization.structure.departments.update');
        Route::delete('/struktura/odjeli/{department}', [StructureController::class, 'destroyDepartment'])->name('organization.structure.departments.destroy');
        Route::post('/struktura/radna-mjesta', [StructureController::class, 'storePosition'])->name('organization.structure.positions.store');
        Route::put('/struktura/radna-mjesta/{position}', [StructureController::class, 'updatePosition'])->name('organization.structure.positions.update');
        Route::delete('/struktura/radna-mjesta/{position}', [StructureController::class, 'destroyPosition'])->name('organization.structure.positions.destroy');
        Route::post('/struktura/mjesta-troska', [StructureController::class, 'storeCostCenter'])->name('organization.structure.cost-centers.store');
        Route::put('/struktura/mjesta-troska/{costCenter}', [StructureController::class, 'updateCostCenter'])->name('organization.structure.cost-centers.update');
        Route::delete('/struktura/mjesta-troska/{costCenter}', [StructureController::class, 'destroyCostCenter'])->name('organization.structure.cost-centers.destroy');
        Route::post('/struktura/pravne-osobe', [StructureController::class, 'storeLegalEntity'])->name('organization.structure.legal-entities.store');
        Route::put('/struktura/pravne-osobe/{legalEntity}', [StructureController::class, 'updateLegalEntity'])->name('organization.structure.legal-entities.update');
        Route::delete('/struktura/pravne-osobe/{legalEntity}', [StructureController::class, 'destroyLegalEntity'])->name('organization.structure.legal-entities.destroy');
        Route::post('/struktura/poslovnice', [StructureController::class, 'storeWorkCenter'])->name('organization.structure.work-centers.store');
        Route::put('/struktura/poslovnice/{workCenter}', [StructureController::class, 'updateWorkCenter'])->name('organization.structure.work-centers.update');
        Route::delete('/struktura/poslovnice/{workCenter}', [StructureController::class, 'destroyWorkCenter'])->name('organization.structure.work-centers.destroy');
        Route::post('/struktura/poslovne-jedinice', [StructureController::class, 'storeEnterpriseUnit'])->name('organization.structure.enterprise-units.store');
        Route::put('/struktura/poslovne-jedinice/{enterpriseUnit}', [StructureController::class, 'updateEnterpriseUnit'])->name('organization.structure.enterprise-units.update');
        Route::delete('/struktura/poslovne-jedinice/{enterpriseUnit}', [StructureController::class, 'destroyEnterpriseUnit'])->name('organization.structure.enterprise-units.destroy');
        Route::get('/kadrovi', [PersonController::class, 'index'])->name('organization.people.index');
        Route::get('/kadrovi/novi', [PersonController::class, 'create'])->name('organization.people.create');
        Route::get('/kadrovi/maticna-knjiga', [PeopleRegisterController::class, 'book'])->name('organization.people.book');
        Route::get('/kadrovi/izvoz', [PeopleRegisterController::class, 'export'])->name('organization.people.export');
        Route::get('/kadrovi/fluktuacija', [PeopleRegisterController::class, 'turnover'])->name('organization.people.turnover');
        Route::get('/kadrovi/place', [PeopleRegisterController::class, 'payroll'])->name('organization.people.payroll');
        Route::get('/kadrovi/place/izvoz', [PeopleRegisterController::class, 'payrollExport'])->name('organization.people.payroll-export');
        Route::post('/kadrovi', [PersonController::class, 'store'])->name('organization.people.store');
        Route::get('/kadrovi/{person}/pregled', [PersonController::class, 'review'])->name('organization.people.review');
        Route::get('/kadrovi/{person}/iskaznica', [PersonPrintController::class, 'badge'])->name('organization.people.badge');
        Route::post('/kadrovi/{person}/qr', [PersonController::class, 'rotateQr'])->name('organization.people.qr.rotate');
        Route::post('/kadrovi/{person}/clock-token', [PersonController::class, 'rotateClockToken'])->name('organization.people.clock-token.rotate');
        Route::get('/kadrovi/{person}/clanak-10', [PersonPrintController::class, 'articleTen'])->name('organization.people.article-ten');
        Route::get('/kadrovi/{person}/uor', [PersonPrintController::class, 'contract'])->name('organization.people.contract');
        Route::get('/kadrovi/{person}/uputnica', [PersonPrintController::class, 'referral'])->name('organization.people.referral');
        Route::get('/kadrovi/{person}/uredi', [PersonController::class, 'edit'])->name('organization.people.edit');
        Route::put('/kadrovi/{person}', [PersonController::class, 'update'])->name('organization.people.update');
        Route::post('/kadrovi/{person}/kvalifikacije', [QualificationController::class, 'store'])->name('organization.qualifications.store');
        Route::delete('/kadrovi/{person}/kvalifikacije/{qualification}', [QualificationController::class, 'destroy'])->name('organization.qualifications.destroy');
        Route::post('/kadrovi/{person}/dokumenti', [PersonDocumentController::class, 'store'])->name('organization.documents.store');
        Route::get('/kadrovi/{person}/dokumenti/{document}/preuzmi', [PersonDocumentController::class, 'download'])->name('organization.documents.download');
        Route::get('/kadrovi/{person}/predlosci/{template}', [PersonDocumentController::class, 'fill'])->name('organization.documents.fill');
        Route::post('/kadrovi/{person}/predlosci/{template}', [PersonDocumentController::class, 'fillStore'])->name('organization.documents.fill-store');
        Route::delete('/kadrovi/{person}/dokumenti/{document}', [PersonDocumentController::class, 'destroy'])->name('organization.documents.destroy');
        Route::post('/kadrovi/{person}/ugovori', [EmploymentContractController::class, 'store'])->name('organization.contracts.store');
        Route::delete('/kadrovi/{person}/ugovori/{employmentContract}', [EmploymentContractController::class, 'destroy'])->name('organization.contracts.destroy');
        Route::post('/kadrovi/{person}/cv', [SelectionController::class, 'storeCv'])->name('organization.people.cv.store');
        Route::get('/kadrovi/{person}/cv', [SelectionController::class, 'downloadCv'])->name('organization.people.cv.download');
        Route::delete('/kadrovi/{person}/cv', [SelectionController::class, 'destroyCv'])->name('organization.people.cv.destroy');
        Route::post('/kadrovi/{person}/razgovori', [SelectionController::class, 'storeNote'])->name('organization.people.notes.store');
        Route::delete('/kadrovi/{person}/razgovori/{note}', [SelectionController::class, 'destroyNote'])->name('organization.people.notes.destroy');
        Route::post('/kadrovi/{person}/zaposli', [PersonController::class, 'hire'])->name('organization.people.hire');
        Route::get('/isteci', [ExpiryController::class, 'index'])->name('organization.expiries.index');
        Route::get('/moj-tjedan', [TimesheetController::class, 'mine'])->name('organization.timesheet.mine');
        Route::get('/predaje', [DocumentHandoverController::class, 'index'])->name('organization.handovers.index');
        Route::post('/predaje', [DocumentHandoverController::class, 'store'])->name('organization.handovers.store');
        Route::get('/raspored', [ScheduleController::class, 'index'])->name('organization.schedule.index');
        Route::post('/raspored/posalji-plan', [ScheduleController::class, 'sendPlan'])->name('organization.schedule.plan.send');
        Route::post('/raspored/prenesi-plan', [ScheduleController::class, 'transferPlan'])->name('organization.schedule.plan.transfer');
        Route::post('/raspored/smjene', [ScheduleController::class, 'storeShift'])->name('organization.schedule.shifts.store');
        Route::delete('/raspored/smjene/{shift}', [ScheduleController::class, 'destroyShift'])->name('organization.schedule.shifts.destroy');
        Route::post('/raspored/pravila', [ScheduleController::class, 'storeRule'])->name('organization.schedule.rules.store');
        Route::delete('/raspored/pravila/{rule}', [ScheduleController::class, 'destroyRule'])->name('organization.schedule.rules.destroy');
        Route::post('/raspored/otvorene-smjene', [ScheduleController::class, 'storeOpenShift'])->name('organization.schedule.open.store');
        Route::delete('/raspored/otvorene-smjene/{openShift}', [ScheduleController::class, 'destroyOpenShift'])->name('organization.schedule.open.destroy');
        Route::post('/raspored/otvorene-smjene/{openShift}/preuzmi', [ScheduleController::class, 'claimOpenShift'])->name('organization.schedule.open.claim');
        Route::get('/sihterica', [TimesheetController::class, 'index'])->name('organization.timesheet.index');
        Route::get('/iznimke', [ExceptionQueueController::class, 'index'])->name('organization.exceptions.index');
        Route::post('/iznimke/{entry}/rijesi', [ExceptionQueueController::class, 'resolve'])->name('organization.exceptions.resolve');
        Route::get('/sihterica/inspekcija', [TimesheetController::class, 'inspection'])->name('organization.timesheet.inspection');
        Route::get('/sihterica/inspekcija/izvoz', [TimesheetController::class, 'exportInspection'])->name('organization.timesheet.inspection-export');
        Route::get('/sihterica/fond', [TimesheetReportController::class, 'fund'])->name('organization.timesheet.fund');
        Route::get('/sihterica/fond/izvoz', [TimesheetReportController::class, 'exportFund'])->name('organization.timesheet.fund-export');
        Route::get('/sihterica/sati-place', [TimesheetReportController::class, 'payrollHours'])->name('organization.timesheet.payroll-hours');
        Route::get('/sihterica/sati-place/izvoz', [TimesheetReportController::class, 'exportPayrollHours'])->name('organization.timesheet.payroll-hours-export');
        Route::get('/grant-sati', [GrantHoursController::class, 'index'])->name('organization.grants.index');
        Route::post('/grant-sati/projekti', [GrantHoursController::class, 'storeProject'])->name('organization.grants.projects.store');
        Route::post('/grant-sati', [GrantHoursController::class, 'storeEntry'])->name('organization.grants.store');
        Route::delete('/grant-sati/{entry}', [GrantHoursController::class, 'destroyEntry'])->name('organization.grants.destroy');
        Route::get('/api/payroll/hours', [TimesheetReportController::class, 'apiPayrollHours'])->name('organization.payroll.hours.api');
        Route::get('/sihterica/izvoz', [TimesheetController::class, 'export'])->name('organization.timesheet.export');
        Route::post('/sihterica/zakljucaj', [TimesheetController::class, 'lock'])->name('organization.timesheet.lock');
        Route::post('/sihterica/prenesi-plan', [TimesheetController::class, 'transferPlan'])->name('organization.timesheet.plan');
        Route::get('/sihterica/{person}/punch/{punch}/foto', [TimesheetController::class, 'punchPhoto'])->name('organization.timesheet.photo');
        Route::get('/sihterica/{person}/{date}', [TimesheetController::class, 'show'])->name('organization.timesheet.day');
        Route::post('/sihterica/{person}/{date}/evidencija', [TimesheetController::class, 'storeEvidential'])->name('organization.timesheet.evidential');
        Route::post('/sihterica/{person}/{date}/slog', [TimesheetController::class, 'storeSlog'])->name('organization.timesheet.slog');
        Route::post('/sihterica/{person}/rucni-unos', [TimesheetController::class, 'storeManual'])->name('organization.timesheet.manual');
        Route::get('/zahtjevi', [StaffRequestController::class, 'index'])->name('organization.requests.index');
        Route::get('/kalendar', [AbsenceCalendarController::class, 'index'])->name('organization.absences.calendar');
        Route::get('/zahtjevi/novi', [StaffRequestController::class, 'create'])->name('organization.requests.create');
        Route::post('/zahtjevi', [StaffRequestController::class, 'store'])->name('organization.requests.store');
        Route::get('/zahtjevi/{zahtjev}', [StaffRequestController::class, 'show'])->name('organization.requests.show');
        Route::get('/zahtjevi/{zahtjev}/rjesenje', [StaffRequestController::class, 'decision'])->name('organization.requests.decision');
        Route::post('/zahtjevi/{zahtjev}/odustani', [StaffRequestController::class, 'cancel'])->name('organization.requests.cancel');
        Route::get('/odobrenja', [ApprovalInboxController::class, 'index'])->name('organization.approvals.index');
        Route::post('/odobrenja/{zahtjev}/odobri', [ApprovalInboxController::class, 'approve'])->name('organization.approvals.approve');
        Route::post('/odobrenja/{zahtjev}/odbij', [ApprovalInboxController::class, 'reject'])->name('organization.approvals.reject');
        Route::get('/tim', [OrganizationTeamController::class, 'index'])->name('organization.team.index');
        Route::post('/tim/pozivnice', [OrganizationTeamController::class, 'storeInvite'])->name('organization.team.invite');
        Route::patch('/tim/{member}/uloga', [OrganizationTeamController::class, 'updateRole'])->name('organization.team.update-role');
        Route::delete('/tim/{member}', [OrganizationTeamController::class, 'destroyMember'])->name('organization.team.destroy');
    });
