# Kopiraj u /etc/supervisor/conf.d/ na produkcijskom serveru.

[program:hr-saas-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/hr-saas/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
directory=/var/www/hr-saas
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ubuntu
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/hr-saas-queue.log
stopwaitsecs=3600
